<?xml version="1.0"?>
<package format="3">
  <name>ros_videostreams</name>
  <version>0.0.1</version>
  <description>Arduino-controlled video/audio scrubber</description>
  <maintainer email="ljung6@example.com">ljung6</maintainer>
  <license>MIT</license>
 
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <exec_depend>python3-serial</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>rqt_image_view</exec_depend>
 
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
 